name: ETT approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Label approved pull request
    runs-on: ubuntu-latest
    steps:
      - name: Lable when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: @{{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved man!"
          REMOVE_LABEL: "awaiting%20review"